const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding Sweet Puppies...');

  const puppies = [
    {
      name: 'Luna', breed: 'Golden Retriever', sex: 'Female',
      birthDate: new Date('2026-03-15'), color: 'Blond doré',
      vaccinationStatus: '1ère injection', dewormingStatus: 'À jour',
      weightCurrent: 5.2, weightEstimatedAdult: 28,
      price: 1500, deposit: 375,
      description: 'Luna est une adorable golden retriever au tempérament doux et joueur. Ses parents sont tous deux certifiés LOSH. Elle est habituée aux enfants et aux autres chiens.',
      parentMotherName: 'Dolly', parentFatherName: 'Max',
      featured: true, isActive: true,
      availableFrom: new Date('2026-05-10'),
      imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&q=80',
      imageUrl2: 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?w=800&q=80',
      location: 'Bastogne',
    },
    {
      name: 'Oscar', breed: 'Jack Russell Terrier', sex: 'Male',
      birthDate: new Date('2026-04-01'), color: 'Blanc et feu',
      vaccinationStatus: '1ère injection', dewormingStatus: 'À jour',
      weightCurrent: 3.8, weightEstimatedAdult: 7,
      price: 1200, deposit: 300,
      description: 'Oscar est un jack russel terrier plein d\'énergie et de caractère. Vif et intelligent, il conviendra à une famille active. Déjà sociabilisé avec les enfants et les autres chiens.',
      parentMotherName: 'Pepette', parentFatherName: 'Gaston',
      featured: true, isActive: true,
      availableFrom: new Date('2026-05-27'),
      imageUrl: 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?w=800&q=80',
      location: 'Bastogne',
    },
    {
      name: 'Charlie', breed: 'Labrador Retriever', sex: 'Male',
      birthDate: new Date('2026-03-20'), color: 'Sable',
      vaccinationStatus: '2ème injection', dewormingStatus: 'À jour',
      weightCurrent: 6.5, weightEstimatedAdult: 32,
      price: 1600, deposit: 400,
      description: 'Charlie est un labrador retriever typique : doux, fidèle et débordant d\'affection. Parfait pour une famille avec enfants. Élevé en intérieur, habitué aux caresses et aux câlins.',
      parentMotherName: 'Ruby', parentFatherName: 'Henry',
      featured: true, isActive: true,
      availableFrom: new Date('2026-05-15'),
      imageUrl: 'https://images.unsplash.com/photo-1596495577886-d920f1fb7238?w=800&q=80',
      location: 'Bastogne',
    },
    {
      name: 'Nala', breed: 'Chihuahua', sex: 'Female',
      birthDate: new Date('2026-02-10'), color: 'Fauve',
      vaccinationStatus: 'Complet', dewormingStatus: 'À jour',
      weightCurrent: 1.2, weightEstimatedAdult: 2.5,
      price: 900, deposit: 225,
      description: 'Nala est un chihuahua au caractère bien trempé. Petite mais pleine de personnalité, elle sera la compagne idéale pour une vie en appartement. Propre et déjà sociabilisée.',
      parentMotherName: 'Skye', parentFatherName: 'Ranger',
      featured: false, isActive: true,
      availableFrom: new Date('2026-04-07'),
      imageUrl: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800&q=80',
      location: 'Bastogne',
    },
    {
      name: 'Milo', breed: 'Yorkshire Terrier', sex: 'Male',
      birthDate: new Date('2026-04-10'), color: 'Gris acier et feu',
      vaccinationStatus: '1ère injection', dewormingStatus: 'À jour',
      weightCurrent: 1.1, weightEstimatedAdult: 3.2,
      price: 1300, deposit: 325,
      description: 'Milo est un yorkshire terrier parfaitement typé. Petit mais courageux, il suivra son maître partout. Idéal pour une personne seule ou un couple. Propre et déjà sociabilisé.',
      parentMotherName: 'Lilly', parentFatherName: 'Teddy',
      featured: false, isActive: true,
      availableFrom: new Date('2026-06-05'),
      imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=800&q=80',
      location: 'Bastogne',
    },
    {
      name: 'Plume', breed: 'Bichon Maltais', sex: 'Female',
      birthDate: new Date('2026-03-01'), color: 'Blanc pur',
      vaccinationStatus: '2ème injection', dewormingStatus: 'À jour',
      weightCurrent: 1.8, weightEstimatedAdult: 3.5,
      price: 1700, deposit: 425,
      description: 'Plume est un bichon maltais d\'une élégance rare. Hypoallergénique, elle convient aux personnes sensibles. Très affectueuse et obéissante, elle excelle déjà dans les exercices de base.',
      parentMotherName: 'Neige', parentFatherName: 'Duke',
      featured: true, isActive: true,
      availableFrom: new Date('2026-04-26'),
      imageUrl: 'https://images.unsplash.com/photo-1596495577886-d920f1fb7238?w=800&q=80',
      location: 'Bastogne',
    },
    {
      name: 'Rocky', breed: 'Berger Allemand', sex: 'Male',
      birthDate: new Date('2026-03-25'), color: 'Noir et feu',
      vaccinationStatus: '1ère injection', dewormingStatus: 'À jour',
      weightCurrent: 8.5, weightEstimatedAdult: 38,
      price: 2000, deposit: 500,
      description: 'Rocky est un berger allemand au physique imposant mais au cœur tendre. Loyal et protecteur, il est excellent avec les enfants. Parents LOSH, lignée sélectionnée pour son tempérament équilibré.',
      parentMotherName: 'Daisy', parentFatherName: 'Cooper',
      featured: false, isActive: true,
      availableFrom: new Date('2026-05-20'),
      imageUrl: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=800&q=80',
      location: 'Bastogne',
    },
    {
      name: 'Cookie', breed: 'Shih Tzu', sex: 'Female',
      birthDate: new Date('2026-04-05'), color: 'Blanc et doré',
      vaccinationStatus: '1ère injection', dewormingStatus: 'À jour',
      weightCurrent: 1.5, weightEstimatedAdult: 5,
      price: 1100, deposit: 275,
      description: 'Cookie est un shih tzu adorable au regard expressif. Calme et câline, elle est parfaite pour la vie en appartement. Déjà propre et très sociable avec les humains et les autres animaux.',
      parentMotherName: 'Snow', parentFatherName: 'Coco',
      featured: false, isActive: true,
      availableFrom: new Date('2026-05-31'),
      imageUrl: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=800&q=80',
      location: 'Bastogne',
    },
    {
      name: 'Titan', breed: 'Berger Allemand', sex: 'Male',
      birthDate: new Date('2026-01-15'), color: 'Noir uni',
      vaccinationStatus: 'Complet', dewormingStatus: 'À jour',
      weightCurrent: 22, weightEstimatedAdult: 40,
      price: 2200, deposit: 550,
      description: 'Titan est un berger allemand noir magnifique. Intelligent et obéissant, il excelle déjà dans les exercices d\'obéissance de base. Parfait pour une famille avec jardin. Parents LOSH.',
      parentMotherName: 'Athena', parentFatherName: 'Zeus',
      featured: false, isActive: true,
      availableFrom: new Date('2026-03-12'),
      imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&q=80',
      location: 'Bastogne',
    },
    {
      name: 'Praline', breed: 'Canis Vulgaris', sex: 'Female',
      birthDate: new Date('2026-03-30'), color: 'Doré tacheté',
      vaccinationStatus: '1ère injection', dewormingStatus: 'À jour',
      weightCurrent: 3.2, weightEstimatedAdult: 12,
      price: 999, deposit: 250,
      description: 'Praline est un magnifique spécimen de Canis Vulgaris, une race rare et polyvalente. Douce, affectueuse et joueuse, elle est parfaite pour une famille avec enfants. Une curiosité canine !',
      parentMotherName: 'Honey', parentFatherName: 'Charlie',
      featured: true, isActive: true,
      availableFrom: new Date('2026-05-25'),
      imageUrl: 'https://images.unsplash.com/photo-1544568100-847a948585b9?w=800&q=80',
      location: 'Bastogne',
    },
  ];

  for (const puppy of puppies) {
    await prisma.puppy.create({ data: puppy });
  }

  console.log('✅ 10 chiots créés');
  console.log('🎉 Seeding terminé !');
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
